### ISSUE TITLE
Remove Health & Mana text

### ISSUE THREAD

**Issue by mrrosh** [Ko0z/UnitFramesImproved_Vanilla#1]
The text under the player unit frame "Health" and "Mana" it's not necessary IMO, could it be removed or add an option to enable/disable it?

**Comment by Ko0z** [comment]
This is game default option, you can remove it in Interface Options by unchecking "Status Bar Text".

**Comment by Ko0z** [comment]
I understand now that you meant just the text strings "Health" and "Mana", I'll look in to it

**Comment by Ko0z** [comment]
<a href="http://imgur.com/IBVbcza"><img src="http://i.imgur.com/IBVbcza.png" title="source: imgur.com" /></a>

This is fixed, I will add some commands in the next patch and this will be included as an option.

**Comment by mrrosh** [comment]
Great job! One more thing, can you also provide an option to change the texture and the size?
I'm using this with modui (which I suggested him to implement your addon into his) but the texture changes to the default modui texture (for health bar and mana bar) and doesn't look all that good.

Thank you again, love your work!
