### ISSUE TITLE
addon interference

### ISSUE THREAD

**Issue by brolernus** [Ko0z/UnitFramesImproved_Vanilla#11]
I encountered problems with 2 different addons:

TinyTip:
The Targethealthbar in the tooltip shows as white/grey instead of green.
CT_Unitframes:
Upon log-in,/reload,Feign Death and sometimes on healthregen. ticks the classcolor "resets".
(Possibly because of CT_PlayerFrame_UpdateSBT)
Since CT_Unitframes is possibly causing this issue you might not bother, but it would be nice to have an addon that shows all Targetbuffs (only reason I'm using CT_Unitframes for, because I dislike modui).

![unitframes](https://cloud.githubusercontent.com/assets/24928956/21668684/624dc44e-d304-11e6-9343-79b77792e875.PNG)

**Comment by Ko0z** [comment]
Alright, yea I might not want to make adjustments to be compatible with a specific addon becuase when that addon is compatible some other addon is suddenly not. It's an infinite loop of problems.

I will however look into making UFI show all target buffs! Thanks for reporting.

**Comment by brolernus** [comment]
your v0.99 fixed the tinytip issue, not using ct_unitframes anymore

**Comment by Ko0z** [comment]
@brolernus Alright that's good! 

Yea I will look into that as soon as I got some spare time, I play alot now when Nostalrius is back lol.
