### ISSUE TITLE
Energy and Rage text doesn't update on enemy unitframe

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#15]
Energy and Rage text doesn't update on enemy unitframe. ModUI suffers from the exact same issue and I've reported it on his github as well a few weeks ago

**Comment by Cruzix** [comment]
This is the report I made on ModUI https://github.com/obble/modui/issues/48

**Comment by Ko0z** [comment]
TargetFrame:SetScript("OnUpdate",  function()
		MH3Blizz:PowerUpdate();
	end)

--This fixes it. 👍
