### ISSUE TITLE
Target of target portrait is slightly off set

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#16]
Target of target portrait is slightly off set, you can see the ground in the top left of the target of target portrait here:
![tot](https://cloud.githubusercontent.com/assets/6162744/21684794/68b9fc02-d35f-11e6-8f63-813d74e624c8.PNG)
Minor issue, though its still an issue afterall :p

**Comment by Ko0z** [comment]
@Cruzix This is a wierd one, I can't reproduce this. I have this slight offset even without any addons!

**Comment by Cruzix** [comment]
Interesting... O.o

Well if it has nothing to do with UFI then I guess you won't be able to fix it. Besides this is a really really minor thing tbh

**Comment by roanaes** [comment]
@Ko0z what u mean u cant reproduce it? it even shows on mod main page:
![pic from mod main page](https://i.imgur.com/64UvmIZ.png)

**Comment by Ko0z** [comment]
@roanaes yea, what I meant was that I couldn't find the cause for the issue, even without addons some target of target portraits are unaligned for me. This should be better now however in the most recent patch v1.0b
