### ISSUE TITLE
Option to disable player unit frame pulse effect when in cities

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#17]
When you're in cities the default unit frames will start pulsating in a yellow color which is a bit annoying, would be awesome if you could find a way to get rid of that 👍 

Here's a visual of it:
![player glow](https://cloud.githubusercontent.com/assets/6162744/21695117/b7c39e38-d388-11e6-8e10-2e9a9438f5b0.gif)

**Comment by Ko0z** [comment]
That's an indicator when the character is resting, there's also one but red when character is in combat! This is default features and they are intended to work this way. Might add an option to remove this but that's low priority for now :)

**Comment by Cruzix** [comment]
No problem :), I made a little digging myself and found the commands to hide the glow effects, you can use them for later in case you wanna implement them. I've tested them ingame by putting /script infront and then copy paste the commands and they seem to be doing the job! :p

PlayerStatusTexture:Hide()
PlayerRestGlow:Hide()
PlayerStatusGlow:Hide()
PlayerAttackGlow:Hide()

I havn't seen the combat glow effect before though, but hopefully the last command takes care of that?

I found the commands here: https://forums.wowace.com/showthread.php?t=20156

**Comment by Ko0z** [comment]
@Cruzix Implemented in next patch 👍

**Comment by Cruzix** [comment]
Any chance you can make this feature disable pet combat glow as well? 😄 ❤️  you can see it happening on this screenshot 
![image](https://cloud.githubusercontent.com/assets/6162744/21894235/c42f9b76-d8de-11e6-9f0f-479469531567.png)

**Comment by Ko0z** [comment]
@Cruzix Yes I will, just forgot about it, should be an easy fix 👍
