### ISSUE TITLE
Add option to enable/disable class portraits

### ISSUE THREAD

**Issue by mrrosh** [Ko0z/UnitFramesImproved_Vanilla#2]
Had someone in here: https://www.reddit.com/r/LegacyAddons/comments/5dtjh6/unitframesimproved_vanilla_backport_of/ asking about disabling the class portraits.

Would it be possible to add such an option? Sorry if it exists and I've missed it.

**Comment by Ko0z** [comment]
No, that doesn't exist atm, I will implement a slash command for this option as well in the next patch coming later today!
