### ISSUE TITLE
Option to anchor enemy debuffs to top instead of bottom

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#20]
Option to anchor enemy debuffs to top instead of bottom of the target unitframe.
It's possible to move the enemy debuff frames with the MoveAnything addon with this command "/move TargetFrameBuff1" however there's no way of changing its grow direction from down to up with MoveAnything, so it will just clip through the unitframe if you simply move it.

**Comment by Ko0z** [comment]
Going to close this one becuase there's already an issue that suggest this feature!

**Comment by Cruzix** [comment]
oh shit, my bad - completely missed that
