### ISSUE TITLE
UFI is breaking pet attack ability icon on the pet bar

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#23]
Here's a screenshot of me having all addons disabled except for UFI:
![image](https://cloud.githubusercontent.com/assets/6162744/21955029/4795b61a-da62-11e6-9db6-f3236d6f6ae4.png)

Without UFI it looks normal again

**Comment by Ko0z** [comment]
Im flying to Germany in a couple of hours! Sorry, I'll be back in 8 days!

**Comment by Cruzix** [comment]
All good mate, no hurry 😄, enjoy your time in Germany 👍

**Comment by brolernus** [comment]
line 11 in UnitFramesImproved_Vanilla.lua:
PET_ATTACK_TEXTURE = PetAttackModeTexture:GetTexture();
seems to be causing it

**Comment by Cruzix** [comment]
Anyone got a fix for this?
