### ISSUE TITLE
Flickering hp bar with new modui

### ISSUE THREAD

**Issue by johnnybgood89** [Ko0z/UnitFramesImproved_Vanilla#24]
There is a problem with flickering hp bar with modui-newest version. Check you addon for possible fix

**Comment by Ko0z** [comment]
This is due to changes in modui code. If you want to fix it you have to open modui.toc inside the modui folder and change the two rows that says:

statusbar\gradient.lua
statusbar\smooth.lua

CHANGE TO THIS:

--statusbar\gradient.lua
--statusbar\smooth.lua
