### ISSUE TITLE
DRUID BAR (and energytick)

### ISSUE THREAD

**Issue by roanaes** [Ko0z/UnitFramesImproved_Vanilla#27]
PLEAAAASE, PLEASE PLEASE...

This needs druid bar like this:
![From retail](https://media-curse.cursecdn.com/attachments/62/571/WoWScrnShot_020412_165217.jpg)

Also if there would be option for energy tick that would be great also, then this would be PERFECT!

I beg these features to be implemented :D Otherwise it's really awesome addon and I love it.

edit:
Modui seems to have these features and this is the way it's set on it:
![Modui](https://i.imgur.com/9gn66WZ.png)

Which is really nice, except I don't like modui visually anymore, and also it doesnt support [Enemyframes unit frame features](https://github.com/zetone/enemyFrames ) ((de)buff timers on class portrait).
I just love your addon but I don't think it's complete without these features, as option atleast :((((

**Comment by roanaes** [comment]
Btw if u make just one of those features please let it be energy ticker, its useful to rogues too and standalone druidbar addon works still pretty well, although it would be much nicer if it was integrated like in modui or retail :)

**Comment by Ko0z** [comment]
I know u requested this a long time ago, I'll see what I can do with my spare time going forward! 
Awesome ideas and thanks for requesting!

**Comment by roanaes** [comment]
@Ko0z hi, I havent played much wow lately but i had to login on my druid and check these updates out, and i have to say it seems perfect! even the druid mana bar seems to be working 100% correctly unlike on some other addons it can sometimes show some weird numbers.
