### ISSUE TITLE
duplicate target percentage

### ISSUE THREAD

**Issue by karakusak** [Ko0z/UnitFramesImproved_Vanilla#29]
It shows duplicate hp percentage on target frame. I have tried to fix it but couldnt find a way to solve this. Here is the [screenshot](http://prntscr.com/hep5c1)

**Comment by karakusak** [comment]
fixed issue #30

**Comment by Ko0z** [comment]
have you tried disabling other addons? This is most likely becuase you have an internal addon conflict going on.

**Comment by karakusak** [comment]
yeah you are right tried to disable some of them and found out that automate conflicting this.

**Comment by Ko0z** [comment]
Good thing you solved your issue though! 👍
