### ISSUE TITLE
NPCs wrong color

### ISSUE THREAD

**Issue by mrrosh** [Ko0z/UnitFramesImproved_Vanilla#3]
The NPCs show the warrior health bar color instead of the green color they should have: http://i.imgur.com/Zdl01ks.png .

**Comment by Ko0z** [comment]
That's actually intended, since mobs/npc have different classes as well. This way you know a mob to be caster if it has a mage colored bar. I can add an option to toggle this.

**Comment by mrrosh** [comment]
Alright, I didn't thought of that. Thank you for clarifying.
