### ISSUE TITLE
[Bug] Target Frame Is Messed Up

### ISSUE THREAD

**Issue by phendrome** [Ko0z/UnitFramesImproved_Vanilla#36]
### The Problem
Target frame settings is not getting saved. Let's say you set up how you want your frames to look, you something, set up compact mode along with moving the name position a little bit to your liking. 

The next time you target something, the target frame is reset. Your own frame however is still intact.

### Potential Solutions or Issue Causing It
I believe it is the [beta version of modui](https://github.com/obble/md) causing it. _However_ a previous build of UFI (the new updated one, perhaps a build from a few days ago... was working just fine, and I removed it as I updated this one).

### Two Screenshots Attached
In the screenshots attached you can see how they should look and what happens after you re-target after setting it up.

![during setting it up](https://user-images.githubusercontent.com/2565750/42098721-fc9e9382-7bbb-11e8-91a2-b996666223d7.jpg)
![messed up ufi](https://user-images.githubusercontent.com/2565750/42098722-fcbc1812-7bbb-11e8-8145-022b432014f3.jpg)

**Comment by Ko0z** [comment]
can't reproduce, maybe an addon compatibility issue, did you try to only have UFI enabled and see if it's still a problem?

**Comment by phendrome** [comment]
Hi again,

I seem to have found the issue. It is caused by the addon called DebuffTimers. When it is disabled UFI works fine with the md beta.
