### ISSUE TITLE
Not really an issue but a humble request.

### ISSUE THREAD

**Issue by Ryofu** [Ko0z/UnitFramesImproved_Vanilla#37]
Hello,

Can you please provide or at least give a simple instructions on how to take just the inverted pet frame module from your addon? I'm a fan of default UI, currently using obbles modui but I'd like to pet frame "match" the ToT frame. I have no idea on how to do this, I'd be thankful if you could help.

**Comment by Ko0z** [comment]
You can use this addon and set it up so that it looks like the default one and then only use pet improved via options. Disable Unitframes module in modui and use this addon for unitframes instead, I will not begin to make tutorials on how to mod, sry.
