### ISSUE TITLE
Suggestion: Make the "ModUI mode" use ModUI's class colors

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#4]
I noticed a big difference in the class colors when I tried out the ModUI mode on my hunter and I find ModUI's colors more relaxing for the eye so I would love if you could make this happen

ModUI: http://i.imgur.com/7aR4Ay9.png 
UFI ModUI mode: http://i.imgur.com/wPRMZgg.png

**Comment by Ko0z** [comment]
I see your point, I didnt test the latest version much so this must have slipped through. I'm going away over the weekend so I will look in to this when I get back on Sunday or Monday! Thank you for reporting!

**Comment by Ko0z** [comment]
Decided to look in to this quick now, but I dont get the colors you get. If you look at the imgur file you posted, with modui unitframes, you dont even get the same color on player frame statusbar and target frame statusbar?

I think you might have some addon conflict? Try to only use modui and UnitFramesImproved_Vanilla and see if you still get that uggly color :)

**Comment by Cruzix** [comment]
Both images has matching colors for player/target frames for me, also tried disabling all addons except modui and ufi, same results (Using latest version of both)

**Comment by Cruzix** [comment]
Just tried downloading the addon hes refering to here: https://github.com/obble/modui/issues/34#issuecomment-262908865 

Exactly same result, the light green colored health bars (only modui + modui_ified enabled)

**Comment by Cruzix** [comment]
Just recorded a video showcasing;
1. ModUI
2. ModUI + UFI
3. ModUI + ModUI ified
https://youtu.be/lC---45MZCc

2 & 3 has the same light class colors while 1 has some completely different ones

I installed complete fresh versions of all 3 addons before recording

**Comment by Ko0z** [comment]
Thank you for your dedication! 

Yes for some reason the healthbar/manabar gets a bit tinted. I will try to fix this once and for all today :)

**Comment by Ko0z** [comment]
@Cruzix Ok so I have fixed the colors on the PlayerFrame. <a href="http://imgur.com/TvYoc3Z"><img src="http://i.imgur.com/TvYoc3Z.png" title="source: imgur.com" /></a>
The more accurate colors is actually the old colors, but I agree the new color is more nice to the eyes.

Will fix TargetFrameHealthBar now and then update.
Cheers.

**Comment by Ko0z** [comment]
**Color comparison between modUI and UFI**
<a href="http://imgur.com/brjtMlN"><img src="http://i.imgur.com/brjtMlN.png" title="source: imgur.com" /></a>
