### ISSUE TITLE
Suggestion: Add an option to change Healthbar/Powerbar texture

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#6]
Any chance you could add an option to change textures for healthbar/powerbar? :)

**Comment by Ko0z** [comment]
@Cruzix Also a nice suggestion! When I get some time I'll look into it!

**Comment by Cruzix** [comment]
would appreciate if you could add a "flat" looking texture similar to the one when using modUI and UFI together 👍

**Comment by Svetsnaz** [comment]
I personally prefer the original texture but unfortunately it is replaced when using modui, would love it if you could toggle the two textures independently
