### ISSUE TITLE
Suggestion: Add option to customize status text

### ISSUE THREAD

**Issue by Cruzix** [Ko0z/UnitFramesImproved_Vanilla#7]
Would be nice if you could add an option to customize how the status text is being shown, an option for %, current and max health + a way to position them. 

http://i.imgur.com/vdobk3N.jpg 
Thats how I would like my status text to be shown but % on the right side and current on the left but thats currently not possible

**Comment by Ko0z** [comment]
@Cruzix I'll add this when I get time! Thanks for the suggestion!

**Comment by Cruzix** [comment]
Also, does Mobhealth3 not work with UFI? I couldnt make it show enemy target status text the other day with Mobhealth3.

**Comment by Ko0z** [comment]
I will have to look into that, thanks for reporting

**Comment by Ko0z** [comment]
MobHealth3 don't even work without UFI for me so I wont bother trying to get that to work when MobInfo2 does the job just fine. I'm considering to integrate MobInfo2 into the addon becuase of some local variables I cant access otherwise

**Comment by Cruzix** [comment]
I've always used Mobhealth3 and its the more common addon to use as it does what its supposed to and nothing else. Mobinfo2 does thousands of different things which is why most people prefer Mobhealth3 but yeah I couldnt get it to work on retro-wow even though it works fine with ModUI that has it integrated. Weird.

**Comment by Ko0z** [comment]
Yea I see your point. MobInfo2 does a lot of unnecessary stuff and the only thing we need really, is it to display HP/MP. I'll look into MobHealth3 again and try to figure out what's wrong with it. It didnt work for me on K2 either.
